ACINQ/bitcoin-kmp

build.gradle.kts, src/commonMain/kotlin/fr/acinq/bitcoin/Block.kt, src/commonMain/kotlin/fr/acinq/bitcoin/ByteVector.kt, src/commonMain/kotlin/fr/acinq/bitcoin/DeterministicWallet.kt, src/commonMain/kotlin/fr/acinq/bitcoin/PrivateKey.kt, src/commonMain/kotlin/fr/acinq/bitcoin/PublicKey.kt, src/commonMain/kotlin/fr/acinq/bitcoin/Satoshi.kt, src/commonMain/kotlin/fr/acinq/bitcoin/Transaction.kt, src/commonTest/kotlin/fr/acinq/bitcoin/ByteVectorTestsCommon.kt
This PR makes certain classes Serializable with KotlinX.Serialization: `BlockHeader` , `ByteVector`, `ByteVector32`, `ByteVector64`, `DeterministicWallet.ExtendedPrivateKey`, `DeterministicWallet.ExtendedPublicKey`, `KeyPath`, `PrivateKey`, `PublicKey`, `Satoshi`, `OutPoint`, `ScriptWitness`, `TxIn`, `TxOut`, `Transaction`.
Because a serializable class must not have property fields outside of its constructor unless marked `@Transient`, fast-computed properties where transformed as getters functions while slow computed properties where marked `@Transient`. 
Note: `ByteVectorX` classes are actually serialized into hexadecimal `String`, because:
- This allows for easier inspection (when using CBOR with tools like [cbor.me](https://cbor.me)).
- When using JSON, this actually saves a lot of …
=> Version `0.3.0-1.4-rc`: Some data classes are now serializable.

src/commonMain/kotlin/fr/acinq/bitcoin/Psbt.kt, src/commonMain/kotlin/fr/acinq/bitcoin/crypto/Pack.kt, src/commonMain/kotlin/fr/acinq/bitcoin/io/Input.kt
We always want readNBytes to check whether there are enough bytes before reading to avoid unexpected exceptions.
I'm not sure what to do with the `intXXX` readers that rely on this: should they also return a nullable value instead of throwing?
=> Strict input bytes reading

src/commonTest/kotlin/fr/acinq/bitcoin/DeterministicWalletTestsCommon.kt
A new test vector was introduced in bitcoin/bips#1030 because some wallets didn't handle leading zeros correctly in
hardened derivation.
We already handled that case correctly, but didn't have a test vector for it.
=> Add hardened derivation leading zeros test

README.md, src/commonMain/kotlin/fr/acinq/bitcoin/Bech32.kt, src/commonTest/kotlin/fr/acinq/bitcoin/Bech32TestsCommon.kt, src/commonTest/resources/data/key_io_valid.json
This support will be necessary for future P2TR addresses.
We add forward-compatible support for segwit v1-16 as suggested in [BIP 350](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki).
=> Add support for Bech32m

src/commonMain/kotlin/fr/acinq/bitcoin/Bitcoin.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BitcoinTestsCommon.kt
The implementation was completely wrong whenever we were updating something else than the first or last element.
=> Fix List.updated

src/commonMain/kotlin/fr/acinq/bitcoin/Psbt.kt, src/commonTest/kotlin/fr/acinq/bitcoin/PsbtTestsCommon.kt
Add more structure to PSBT inputs and outputs.
The main change is to split segwit and non-segwit inputs, as they have different requirements.
A higher-level application will always know whether the inputs it's responsible for use segwit or not, so they'll be able to take advantage of these new types (instead of manually parsing the PSBT fields themselves).
=> Improve PSBT types

README.md
Took me a second to figure out why the dependency couldn't be found.
=> Fix typo referencing wrong maven group id

src/commonMain/kotlin/fr/acinq/bitcoin/Bech32.kt, src/commonTest/kotlin/fr/acinq/bitcoin/Bech32TestsCommon.kt
When the application already provides a checksum mechanism, it doesn't need to rely on the bech32 checksum.
In particular, this lets eclair work with Bolt 12 offers without having to re-implement the bech32 logic.
=> Add support for bech32 without checksums

src/commonMain/kotlin/fr/acinq/bitcoin/Bech32.kt, src/commonTest/kotlin/fr/acinq/bitcoin/Bech32TestsCommon.kt
Add functions to encode and decode bytes with bech32. We previously forced the caller to convert to 5-bit data, but we can hide
that implementation detail for some applications.
@thomash-acinq let me know if that makes sense for offers, I believe that's what we'd use, wouldn't we?
=> Encode and decode arbitrary bytes with bech32

src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt
This PR creates a test for the huge `OP_SUCCESSx` tx created by [@brqgoo](https://twitter.com/brqgoo/status/1587397646125260802) in tx [73be398c4bdc43709db7398106609eea2a7841aaf3a4fa2000dc18184faa2a7e](https://blockstream.info/tx/73be398c4bdc43709db7398106609eea2a7841aaf3a4fa2000dc18184faa2a7e) and discussed in btcd issue [#1906]( https://github.com/btcsuite/btcd/issues/1906)
This transaction shouldn't be relayed, but once mined will be considered valid by bitcoin-kmp.
=> Add test for large opSuccess tx

build.gradle.kts, src/commonMain/kotlin/fr/acinq/bitcoin/Crypto.kt, src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt, src/commonMain/kotlin/fr/acinq/bitcoin/ScriptTree.kt, src/commonMain/kotlin/fr/acinq/bitcoin/XonlyPublicKey.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BIP86TestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/reference/BIP341TestsCommon.kt
This will make bitcoin-kmp easier to use from bitcoin-lib and eclair. The biggest change is the definition of TaprootTweak, which has now a flat hierarchy (it was just unusable from Scala and I did not want to create a Scala clone for this flag).
We also upgrade secp256k1-kmp which now is based on secp256k1 0.2.0
=> Simple changes to make this library more scala-friendly

src/commonMain/kotlin/fr/acinq/bitcoin/Transaction.kt, src/commonTest/kotlin/fr/acinq/bitcoin/reference/TransactionTestsCommon.kt
This is useful when sharing on-chain fees in the interactive-tx protocol used in lightning for dual funding and splicing.
=> Add weight() to TxIn and TxOut

build.gradle.kts, src/commonMain/kotlin/fr/acinq/bitcoin/Bitcoin.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BIP86TestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BitcoinTestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/ScriptTestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt
We add specific return types to handle invalid address and public key script conversions. 
This is better than throwing exceptions because it makes easier for clients to create their own error handling code with localized error messages.
=> Use proper types for address and script conversion errors

src/commonMain/kotlin/fr/acinq/bitcoin/psbt/Psbt.kt
This makes it nicer to use from Scala by creating a backing field instead of having to use a getter function.
Unfortunately we cannot do that for the various `Input`s and `Output`s, as Kotlin doesn't support this feature on abstract fields.
=> Add JvmField on PSBT fields

src/commonMain/kotlin/fr/acinq/bitcoin/Crypto.kt, src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt, src/commonMain/kotlin/fr/acinq/bitcoin/ScriptTree.kt, src/commonMain/kotlin/fr/acinq/bitcoin/Transaction.kt, src/commonMain/kotlin/fr/acinq/bitcoin/XonlyPublicKey.kt, src/commonTest/kotlin/fr/acinq/bitcoin/Musig2TestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/reference/BIP341TestsCommon.kt
We provide helpers and better high-level abstractions for spending taproot outputs via either the key path or script path. This ensures that callers can't mess up which `SigVersion` they use, or forget to include the script leaf hash or merkle root depending on what they are spending.
The caller only needs to remember:
- the internal public key
- the script tree
- if they're using the script path, the ID of the script leaf they're using
That is information that they should always be able to keep around or recompute, and seems to be minimal.
NB: the two commits are somewhat independent and should be reviewed separately.
=> Provide high-level taproot abstractions

build.gradle.kts, src/commonMain/kotlin/fr/acinq/bitcoin/Bitcoin.kt, src/commonMain/kotlin/fr/acinq/bitcoin/utils/Either.kt, src/commonMain/kotlin/fr/acinq/bitcoin/utils/Try.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BIP86TestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BitcoinTestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/ScriptTestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt
We already export an `Either` type, which can be reused by clients of this library.
=> Use Either for error handling

src/commonMain/kotlin/fr/acinq/bitcoin/Bitcoin.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BitcoinTestsCommon.kt
Kotlin inner classes are not supported in Swift, and require workarounds, which are not even possible if the class is used throughout a project. We should avoid inner classes as much as possible.
For example: if you have outer class `Foo` and inner class `Bar`, then `Foo.Bar` doesn't appear within Swift. But also any function that uses `Foo.Bar` as either a parameter or return type is also unavailable in Swift.
Note: This may be fixed with https://skie.touchlab.co, but it's better to not have to use a generator in the first place.
=> Pulls the Chain inner-class out of the Bitcoin object

src/commonMain/kotlin/fr/acinq/bitcoin/Bitcoin.kt, src/commonMain/kotlin/fr/acinq/bitcoin/PublicKey.kt, src/commonMain/kotlin/fr/acinq/bitcoin/XonlyPublicKey.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BIP86TestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt
BIP86 is very similar to BIP84 and allows deriving single-key addresses for taproot addresses (instead of p2wpkh addresses). These addresses use a deterministic tweak that ensures that there is no script path associated with that address.
=> Add BIP86 address helpers

src/commonMain/kotlin/fr/acinq/bitcoin/Block.kt, src/commonMain/kotlin/fr/acinq/bitcoin/DeterministicWallet.kt, src/commonMain/kotlin/fr/acinq/bitcoin/Transaction.kt, src/commonTest/kotlin/fr/acinq/bitcoin/DeterministicWalletTestsCommon.kt
Member methods (in addition to static methods) will make this library easier to use, especially from IDE/editors that implement code completion features.
=> Add member methods to improve usability

build.gradle.kts, src/commonMain/kotlin/fr/acinq/bitcoin/psbt/Psbt.kt, src/commonTest/kotlin/fr/acinq/bitcoin/psbt/PsbtTestsCommon.kt
We only add what is necessary to create, update and sign taproot (BIP86) outputs.
=> Add partial support for PSBT Taproot Fields (BIP371)

src/commonMain/kotlin/fr/acinq/bitcoin/Bech32.kt, src/commonMain/kotlin/fr/acinq/bitcoin/Bitcoin.kt, src/commonMain/kotlin/fr/acinq/bitcoin/Block.kt, src/commonMain/kotlin/fr/acinq/bitcoin/Descriptor.kt, src/commonMain/kotlin/fr/acinq/bitcoin/PublicKey.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BIP49TestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BIP86TestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/BitcoinTestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/DeriveWalletKeysTestsCommon.kt, src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt
See https://github.com/bitcoin/bitcoin/pull/29775.
It basically adds a new genesis block the testnet4 (addresses uses the same prefixes/encoding as testnet3).
=> Add support for testnet4

build.gradle.kts, src/commonMain/kotlin/fr/acinq/bitcoin/crypto/musig2/Musig2.kt, src/commonTest/kotlin/fr/acinq/bitcoin/crypto/musig2/Musig2TestsCommon.kt
Add a high-level method to verify partial musig2 signatures.
We also export `secp256k1-kmp` method to generate musig2 nonces from a counter.
=> Add musig2 verification helper

build.gradle.kts, src/commonMain/kotlin/fr/acinq/bitcoin/crypto/musig2/Musig2.kt, src/commonTest/kotlin/fr/acinq/bitcoin/crypto/musig2/Musig2TestsCommon.kt
We used kotlin's ULong type for the counter arguments which mangles method names when used from Scala. We also add an alternate method for nonce generation that includes new paramaters (message and additional data) and deprecate (but keep) the old one.
=> Fix musig2 counter-based nonce generation API
